In [1]:
!pip install ET-eds-api --upgrade --quiet

In [2]:
from ET_eds_api import get_wp_h, wagg_wp, VE, columns

In [3]:
wp_h, q_h = get_wp_h(start=2024, end=2025)
wp_h.head()

/Users/linuslindquist/Desktop/eds-api/ET_eds_api/fetcher_p.py:61: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  p_combined = pd.concat([

              HourUTC  SpotPriceDKK_weighted
0 2024-01-01 00:00:00             210.646841
1 2024-01-01 01:00:00             198.740005
2 2024-01-01 02:00:00              80.149905
3 2024-01-01 03:00:00              57.280877
4 2024-01-01 04:00:00              37.534504

In [4]:
solar_ve = VE(
    value_columns = ["SolarPowerLt10kW_MWh", "SolarPowerGe10Lt40kW_MWh", "SolarPowerGe40kW_MWh"],
    cap_column    = ["SolarPowerCapacity"],
    col_name      = "solar_VE",
    start         = 2024,
    end           = 2025,
)
solar_ve.head()

Index denominator is: ===================

month                 2024-12-01 00:00:00
SolarPowerCapacity             3913.23882
solar_VE_idx                          1.0
Name: 11, dtype: object

              HourUTC      month     value  solar_VE_idx  solar_VE
0 2024-01-01 00:00:00 2024-01-01  0.248109      0.904125  0.274419
1 2024-01-01 01:00:00 2024-01-01  0.268686      0.904125  0.297178
2 2024-01-01 02:00:00 2024-01-01  0.276260      0.904125  0.305555
3 2024-01-01 03:00:00 2024-01-01  0.239684      0.904125  0.265101
4 2024-01-01 04:00:00 2024-01-01  0.317000      0.904125  0.350615

In [5]:
columns()

── value_columns (ProductionConsumptionSettlement) ──
  OffshoreWindLt100MW_MWh
  OffshoreWindGe100MW_MWh
  OnshoreWindLt50kW_MWh
  OnshoreWindGe50kW_MWh
  SolarPowerLt10kW_MWh
  SolarPowerGe10Lt40kW_MWh
  SolarPowerGe40kW_MWh
  ExchangeNO_MWh
  ExchangeSE_MWh
  ExchangeGE_MWh
  ExchangeNL_MWh
  ExchangeGB_MWh
  ExchangeGreatBelt_MWh

── cap_column (CapacityPerMunicipality) ──
  CapacityGe100MW
  CapacityLt100MW
  OffshoreWindCapacity
  OnshoreWindCapacity
  SolarPowerCapacity